/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myjavaproject;

/**
 *
 * @author bryan
 */
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.*;
import javax.sql.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import admin.*;
import conexion.*;
import java.awt.*;
public class addnota extends javax.swing.JFrame {

    /**
     * Creates new form addnota
     */
      private ImageIcon imagen;
    private Icon icono;
    public addnota() {
        initComponents();
         this.setLocationRelativeTo(this);
        this.ajustarImagen(jLabel2, null);
        
        this.ajustarImagen(jLabel2, "src/img/logo-uts.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonLight = new javax.swing.JButton();
        jButtonDark = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(195, 215, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MiApUTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-uts.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 70, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Id_Aputs");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("INSERCIÓN DE CALIFICACIÓN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Recuerde, no podrá modificar su calificación despues de su inserción");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Calificación");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 200, -1));

        jButton1.setText("INSERTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jButton2.setText("VOLVER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jButtonLight.setText("Modo Claro");
        jButtonLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLightActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jButtonDark.setText("Modo Oscuro");
        jButtonDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDarkActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Advertencia
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "⚠ La calificación NO podrá modificarse después.\n¿Desea continuar?",
            "Confirmar inserción",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );
    
    if (confirm != JOptionPane.YES_OPTION) {
        return; // si elige NO, se cancela
    }

    // Obtener datos de los textfields
    String idAputsTxt = jTextField1.getText().trim();
    String calificacionTxt = jTextField2.getText().trim();

    // Validaciones
    if (idAputsTxt.isEmpty() || calificacionTxt.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
        return;
    }

    int idAputs;
    int calificacion;

    try {
        idAputs = Integer.parseInt(idAputsTxt);
        calificacion = Integer.parseInt(calificacionTxt);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Los valores deben ser numéricos.");
        return;
    }

    // Rango válido (si aplica)
    if (calificacion < 0 || calificacion > 5) {
        JOptionPane.showMessageDialog(null, "La calificación debe estar entre 0 y 5.");
        return;
    }

    // Conexión e inserción
    connect conn = new connect();
    Connection con = conn.connect();

    String sql = "INSERT INTO calificaciones (id_usuario, id_aputs, calificacion) VALUES (?, ?, ?)";

    try {
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, user.id);   // Usuario logueado automáticamente
        ps.setInt(2, idAputs);
        ps.setInt(3, calificacion);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Calificación registrada correctamente.");

        // Cerrar ventana y volver a la lista (opcional)
        this.dispose();
        notas n = new notas();
        n.setVisible(true);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al insertar: " + e.toString());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        notas n = new notas();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDarkActionPerformed
        this.activarModoOscuro();
    }//GEN-LAST:event_jButtonDarkActionPerformed

    private void jButtonLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLightActionPerformed
        // TODO add your handling code here:
        this.activarModoClaro();
    }//GEN-LAST:event_jButtonLightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addnota().setVisible(true);
            }
        });
    }
     private void ajustarImagen(JLabel jLabel3, String ruta ){
    this.imagen = new ImageIcon(ruta);
    this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(),Image.SCALE_DEFAULT));
    jLabel3.setIcon(this.icono);
    this.repaint();
    }
private void activarModoOscuro() {

    // Paneles
    jPanel1.setBackground(new Color(35,35,35));
    jPanel2.setBackground(new Color(25,25,25));

    // Labels
    JLabel[] labels = { jLabel1, jLabel3, jLabel4, jLabel5, jLabel7 };
    for (JLabel l : labels) {
        l.setForeground(Color.WHITE);
    }

    // Textfields
    JTextField[] fields = { jTextField1, jTextField2 };
    for (JTextField t : fields) {
        t.setBackground(new Color(70,70,70));
        t.setForeground(Color.WHITE);
        t.setCaretColor(Color.WHITE);
        t.setBorder(BorderFactory.createLineBorder(new Color(120,120,120)));
    }

    // Botones
    JButton[] botones = { jButton1, jButton2, jButtonDark, jButtonLight };
    for (JButton b : botones) {
        b.setBackground(new Color(70,130,180));
        b.setForeground(Color.WHITE);
    }

    JOptionPane.showMessageDialog(this, "Modo oscuro activado");
}

private void activarModoClaro() {

    // Paneles
    jPanel1.setBackground(Color.WHITE);
    jPanel2.setBackground(new Color(195,215,48));

    // Labels
    JLabel[] labels = { jLabel1, jLabel3, jLabel4, jLabel5, jLabel7 };
    for (JLabel l : labels) {
        l.setForeground(Color.BLACK);
    }

    // El texto blanco del encabezado
    jLabel1.setForeground(Color.WHITE);

    // Textfields
    JTextField[] fields = { jTextField1, jTextField2 };
    for (JTextField t : fields) {
        t.setBackground(Color.WHITE);
        t.setForeground(Color.BLACK);
        t.setCaretColor(Color.BLACK);
        t.setBorder(UIManager.getBorder("TextField.border"));
    }

    // Botones
    JButton[] botones = { jButton1, jButton2, jButtonDark, jButtonLight };
    for (JButton b : botones) {
        b.setBackground(UIManager.getColor("Button.background"));
        b.setForeground(Color.BLACK);
    }

    JOptionPane.showMessageDialog(this, "Modo claro restaurado");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDark;
    private javax.swing.JButton jButtonLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
