/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myjavaproject;
import java.awt.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.*;
import javax.sql.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import admin.*;
import conexion.*;

/**
 *
 * @author bryan
 */
public class more extends javax.swing.JFrame {

    /**
     * Creates new form more
     */
     private ImageIcon imagen;
    private Icon icono;
    public more() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.ajustarImagen(jLabel2, null);
        
        this.ajustarImagen(jLabel2, "src/img/logo-uts.png");
        this.ajustarImagen(jLabel3, "src/img/csoon.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonLight = new javax.swing.JButton();
        jButtonDark = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(198, 215, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MiApUTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-uts.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 10, 90, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("EXPORTAR REPORTE EN TXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/csoon.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 370, 140));

        jButton2.setText("VOLVER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jButtonLight.setText("Modo Claro");
        jButtonLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLightActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jButtonDark.setText("Modo Oscuro");
        jButtonDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDarkActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        connect con = new connect();
    Connection cn = con.connect();

    int idUsuario = user.id;

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar reporte");

    fileChooser.setSelectedFile(new java.io.File("reporte_aputs_ID_" + idUsuario + ".txt"));

    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection != JFileChooser.APPROVE_OPTION) {
        return; // cancelado
    }

    java.io.File fileToSave = fileChooser.getSelectedFile();

    try {
        String sql = "SELECT titulo, evento, apuesta, cuota, apostado, ganancia, estado, id_usuario FROM aputs WHERE id_usuario = ?";
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setInt(1, idUsuario);
        ResultSet rs = pst.executeQuery();

        java.io.FileWriter fw = new java.io.FileWriter(fileToSave);
        fw.write("===== REPORTE DE APUTS =====\n");
        fw.write("Usuario ID: " + idUsuario + "\n\n");

        int contador = 0;

        while (rs.next()) {

            fw.write("----- APUT #" + (contador + 1) + " -----\n");
            fw.write("Titulo: " + rs.getString("titulo") + "\n");
            fw.write("Evento: " + rs.getString("evento") + "\n");
            fw.write("Apuesta: " + rs.getString("apuesta") + "\n");
            fw.write("Cuota: " + rs.getString("cuota") + "\n");
            fw.write("Apostado: " + rs.getString("apostado") + "\n");
            fw.write("Ganancia: " + rs.getString("ganancia") + "\n");
            fw.write("Estado: " + rs.getString("estado") + "\n");
            fw.write("ID Usuario: " + rs.getInt("id_usuario") + "\n\n");

            contador++;
        }

        fw.write("Total de APUTS: " + contador + "\n");
        fw.close();

        JOptionPane.showMessageDialog(null, "Reporte generado exitosamente:\n" + fileToSave.getAbsolutePath());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error generando reporte: " + e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        main m = new main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDarkActionPerformed
        this.activarModoOscuro();
    }//GEN-LAST:event_jButtonDarkActionPerformed

    private void jButtonLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLightActionPerformed
       this.activarModoClaro();
    }//GEN-LAST:event_jButtonLightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(more.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new more().setVisible(true);
            }
        });
    }
    private void ajustarImagen(JLabel jLabel3, String ruta ){
    this.imagen = new ImageIcon(ruta);
    this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(),Image.SCALE_DEFAULT));
    jLabel3.setIcon(this.icono);
    this.repaint();
    }
    private void activarModoOscuro() {

    // Panels
    jPanel1.setBackground(new Color(25,25,25));
    jPanel2.setBackground(new Color(15,15,15));
    jPanel3.setBackground(new Color(30,30,30));

    // Labels
    JLabel[] labels = { jLabel1 };
    for (JLabel l : labels) {
        l.setForeground(Color.WHITE);
    }

    // Botones
    JButton[] botones = { jButton1, jButton2, jButtonDark, jButtonLight };
    for (JButton b : botones) {
        b.setBackground(new Color(70,130,180));
        b.setForeground(Color.WHITE);
    }

    JOptionPane.showMessageDialog(this, "Modo oscuro activado");
}
private void activarModoClaro() {

    jPanel1.setBackground(Color.WHITE);
    jPanel2.setBackground(new Color(198,215,48));
    jPanel3.setBackground(Color.WHITE);

    jLabel1.setForeground(Color.WHITE); // el texto del header siempre va blanco

    JButton[] botones = { jButton1, jButton2, jButtonDark, jButtonLight };
    for (JButton b : botones) {
        b.setBackground(UIManager.getColor("Button.background"));
        b.setForeground(Color.BLACK);
    }

    JOptionPane.showMessageDialog(this, "Modo claro restaurado");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDark;
    private javax.swing.JButton jButtonLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
